---
- name: Install flatpak
  ansible.builtin.apt:
    name: flatpak
    state: present

- name: Add flathub remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install flatpak applications
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    remote: flathub
  loop: "{{ flatpak_apps }}"
