---
- name: Check if i386 architecture is enabled
  ansible.builtin.command: dpkg --print-foreign-architectures
  register: foreign_archs
  changed_when: false

- name: Enable i386 multiarch for Steam
  ansible.builtin.command: dpkg --add-architecture i386
  when: "'i386' not in foreign_archs.stdout_lines"

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install Debian packages
  ansible.builtin.apt:
    name: "{{ debian_packages }}"
    state: present

- name: Install third-party packages
  ansible.builtin.apt:
    name: "{{ third_party_packages }}"
    state: present

- name: Install best-effort packages
  ansible.builtin.apt:
    name: "{{ best_effort_packages }}"
    state: present
  ignore_errors: true
