---
- name: Download Go tarball
  ansible.builtin.get_url:
    url: "https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz"
    dest: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
    mode: '0644'

- name: Remove existing Go installation
  ansible.builtin.file:
    path: /usr/local/go
    state: absent

- name: Extract Go
  ansible.builtin.unarchive:
    src: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
    dest: /usr/local
    remote_src: true

- name: Add Go to system PATH
  ansible.builtin.copy:
    dest: /etc/profile.d/go.sh
    content: "export PATH=$PATH:/usr/local/go/bin\n"
    mode: '0644'

- name: Install k9s
  ansible.builtin.unarchive:
    src: https://github.com/derailed/k9s/releases/latest/download/k9s_Linux_amd64.tar.gz
    dest: /usr/local/bin
    remote_src: true
    creates: /usr/local/bin/k9s
    mode: '0755'
