general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Dim the screen after 5 minutes of idling
listener {
    timeout = 300000
    on-timeout = brightnessctl -s set 10%
    on-resume = brightnessctl -r
}

# Lock the session after 10 minutes of idling
listener {
    timeout = 600000
    on-timeout = loginctl lock-session
}
