---
- name: Ensure ~/.local/bin exists
  ansible.builtin.file:
    path: "{{ target_home }}/.local/bin"
    state: directory
    mode: '0755'

- name: Install chezmoi
  ansible.builtin.shell: |
    set -o pipefail
    sh -c "$(curl -fsLS get.chezmoi.io)" -- -b "$HOME/.local/bin"
  args:
    creates: "{{ target_home }}/.local/bin/chezmoi"
  environment:
    HOME: "{{ target_home }}"

- name: Apply dotfiles with chezmoi (from local source)
  ansible.builtin.command: |
    chezmoi init --apply --source {{ chezmoi_source_path }}
  args:
    creates: "{{ target_home }}/.local/share/chezmoi"
  environment:
    HOME: "{{ target_home }}"
  when: chezmoi_source_path | length > 0

- name: Apply dotfiles with chezmoi (from GitHub)
  ansible.builtin.command: |
    chezmoi init --apply {{ chezmoi_repo }}
  args:
    creates: "{{ target_home }}/.local/share/chezmoi"
  environment:
    HOME: "{{ target_home }}"
  when: chezmoi_source_path | length == 0
