---
- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ target_user }}"
    groups: docker
    append: true

- name: Enable and start docker
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started

- name: Enable and start tailscaled
  ansible.builtin.systemd:
    name: tailscaled
    enabled: true
    state: started
