-- Treesitter highlighting is built into Neovim 0.10+ and enabled by default.
--
-- The standalone `nvim-treesitter` plugin was removed here: its `master` branch
-- is archived and its query handling calls APIs removed in Neovim 0.12
-- (`vim.treesitter.get_node_text` -> `get_range` -> `node:range()`), which is
-- what produced the `attempt to call method 'range' (a nil value)` stack trace.
--
-- Install language parsers with the tree-sitter CLI instead:
--   bin/install-treesitter-parsers.sh
-- See `:help treesitter` for how Neovim locates `parser/*.{so,dylib}` on the
-- runtimepath (default: ~/.local/share/nvim/parser).
return {}
